version: '3'
services:
  mongo:
    image: mongo
    volumes:
      - /data/db:/data/db
    ports:
      - 27017:27017 
  
  neo4j:
    image: neo4j:4.0
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - /conf:/conf
      - /data:/data
      - /logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/Welcome1
      
  
  userprofilesvc:
    build:
      context: ./server
      dockerfile: ./SJZ.UserProfileService/Dockerfile
    ports:
      - "5000:80"
    environment:
      - NEO4J_USERNAME=neo4j
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_PASSWORD=Welcome1
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - neo4j

  oauthsvc:
    build:
      context: ./server
      dockerfile: ./SJZ.OAuthService/Dockerfile
    ports:
      - "5010:80"
    environment:
      - UPS_SVC=http://userprofilesvc:80
      - ISSUER=http://localhost:5010
      - GITHUB_CLIENTSECRET=408941d4d7c701efd5a6497e1627e0f8fbd503fc
      - GITHUB_CLIENTID=6abec5f4e4d9d5c48f07
      - LINKEDIN_CLIENTSECRET=FSVHA2ty27qpe8yb
      - LINKEDIN_CLIENTID=81y34iwbqrnk79
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - userprofilesvc
      
  imagesvc:
    build:
      context: ./server
      dockerfile: ./SJZ.ImageService/Dockerfile
    ports:
      - "5020:80"
    environment:
      - STORAGEACCOUNT_CONNECTIONSTRING="DefaultEndpointsProtocol=https;AccountName=storageaccountexp85e8;AccountKey=fZBa58mEvrKqvjaoIKqqy3pkMbgTGkDBuyoh+72J3BzCvgHoS+5miknuNstu4J8RsCKEuw8AsMOHLja1N/XkeA==;EndpointSuffix=core.windows.net"
      - STORAGEACCOUNT_KEY="fZBa58mEvrKqvjaoIKqqy3pkMbgTGkDBuyoh+72J3BzCvgHoS+5miknuNstu4J8RsCKEuw8AsMOHLja1N/XkeA=="
      - AUTHORITY=http://oauthsvc:80
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - oauthsvc
    
      
  timelinesvc:
    build:
      context: ./server
      dockerfile: ./SJZ.TimelineService/Dockerfile
    ports:
      - "5030:80"
    environment:
      - MONGO_DATABASE=sjz
      - MONGO_CONNECTIONSTRING=mongodb://mongo:27017
      - AUTHORITY=http://oauthsvc:80
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - oauthsvc
      - mongo
      
  # angularclient:
    # build:
      # context: ./client
      # dockerfile: ./dev.Dockerfile
    # ports:
      # - 4200:80
    # depends_on:
      # - timelinesvc