version: '3'
services:
  mongo:
    image: mongo
    volumes:
      - /data/db:/data/db
    ports:
      - 27017:27017 
  
  neo4j:
    image: neo4j:4.0
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - /conf:/conf
      - /data:/data
      - /logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      
  
  userprofilesvc:
    build:
      context: ./server
      dockerfile: ./SJZ.UserProfileService/Dockerfile
    ports:
      - "5000:80"
    environment:
      - NEO4J_USERNAME=neo4j
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - neo4j

  oauthsvc:
    build:
      context: ./server
      dockerfile: ./SJZ.OAuthService/Dockerfile
    ports:
      - "5010:80"
    environment:
      - UPS_SVC=http://userprofilesvc:80
      - ISSUER=http://localhost:5010
      - GITHUB_CLIENTSECRET=${GITHUB_CLIENTSECRET}
      - GITHUB_CLIENTID=${GITHUB_CLIENTID}
      - LINKEDIN_CLIENTSECRET=${LINKEDIN_CLIENTSECRET}
      - LINKEDIN_CLIENTID=${LINKEDIN_CLIENTID}
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - userprofilesvc
      
  imagesvc:
    build:
      context: ./server
      dockerfile: ./SJZ.ImageService/Dockerfile
    ports:
      - "5020:80"
    environment:
      - STORAGEACCOUNT_CONNECTIONSTRING=${STORAGEACCOUNT_CONNECTIONSTRING}
      - STORAGEACCOUNT_KEY=${STORAGEACCOUNT_KEY}
      - AUTHORITY=http://oauthsvc:80
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - oauthsvc
    
      
  timelinesvc:
    build:
      context: ./server
      dockerfile: ./SJZ.TimelineService/Dockerfile
    ports:
      - "5030:80"
    environment:
      - MONGO_DATABASE=sjz
      - MONGO_CONNECTIONSTRING=mongodb://mongo:27017
      - AUTHORITY=http://oauthsvc:80
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - oauthsvc
      - mongo
      
  # angularclient:
    # build:
      # context: ./client
      # dockerfile: ./dev.Dockerfile
    # ports:
      # - 4200:80
    # depends_on:
      # - timelinesvc