apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth
  namespace: sjz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth
  template:
    metadata:
      labels:
        app: oauth
    spec:
      containers:
      - name: oauth
        image: sjzvin.azurecr.io/sjz_oauthsvc:{{VERSION_NUMBER}}
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: UPS_SVC
          value: "http://ups:80"
        - name: GITHUB_CLIENTSECRET
          value: "bolt://neo4j:7687"
        - name: GITHUB_CLIENTID
          value: "Welcome1"
        - name: LINKEDIN_CLIENTSECRET
          value:
        - name: LINKEDIN_CLIENTID
          value:
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 1
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 1
          timeoutSeconds: 3
      imagePullSecrets:
      - name: registrysecret
---
apiVersion: v1
kind: Service
metadata:
  name: oauth
  namespace: sjz
  labels:
    app: oauth
spec:
  type: NodePort
  ports:
  - name: web
    port: 80
  selector:
    app: oauth
