apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth
  namespace: sjz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauthsvc
  template:
    metadata:
      labels:
        app: oauthsvc
    spec:
      containers:
      - name: oauthsvc
        image: sjzvin.azurecr.io/sjz_oauthsvc:${VERSION_NUMBER}
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ISSUER
          value: "https://auth.timelines.top"
        - name: UPS_SVC
          value: "http://ups:80"
        - name: GITHUB_CLIENTSECRET
          value: "${GITHUB_CLIENTSECRET}"
        - name: GITHUB_CLIENTID
          value: "${GITHUB_CLIENTID}"
        - name: LINKEDIN_CLIENTSECRET
          value: "${LINKEDIN_CLIENTSECRET}"
        - name: LINKEDIN_CLIENTID
          value: "${LINKEDIN_CLIENTID}"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 1
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 1
          timeoutSeconds: 3
      imagePullSecrets:
      - name: registrysecret
---
apiVersion: v1
kind: Service
metadata:
  name: oauthsvc
  namespace: sjz
  labels:
    app: oauthsvc
spec:
  type: NodePort
  ports:
  - name: web
    port: 80
  selector:
    app: oauthsvc
