apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-neo4j
  labels:
    type: local
    app: neo4j
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/neo4j
    

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-neo4j-core
  labels:
    app: neo4j
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: neo4j
  name: neo4j
  namespace: infra
spec:
  clusterIP: None
  ports:
    - port: 7474
      targetPort: 7474
  selector:
    app: neo4j
    
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: neo4j-core
  namespace: infra
spec:
  serviceName: neo4j
  replicas: 1
  template:
    metadata:
      labels:
        app: neo4j
        role: core
    spec:
      containers:
      - name: neo4j
        image: neo4j:4.0
        env:
          - name: NEO4J_AUTH
            value: neo4j/Welcome1
        ports:
        - containerPort: 7474
          name: browser
        - containerPort: 7687
          name: bolt
        volumeMounts:
        - name: datadir
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: datadir
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi