apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: sjz
spec:
  type: ExternalName
  externalName: mongodb.infra.svc.cluster.local
  ports:
  - port: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: sjz
spec:
  type: ExternalName
  externalName: neo4j.infra.svc.cluster.local
  ports:
  - port: 7474
    port: 7687